feat: Add APIGW origin for Cloudfron
pagopa/interop-infra-probing pull request #32
Opened 2023-04-04 08:52 UTC by alessio-creo

2023-04-05 07:27 UTC, micdes-pagopa requested changes

2023-04-05 07:27 UTC, micdes-pagopa commented on src/main/31-cloudfront.tf
> +      domain_name = "${aws_api_gateway_rest_api.apigw.id}.execute-api.${var.aws_region}.amazonaws.com"
Use the`invoke_url` attribute from the APIGW stage. Note that if you use that you won't need `origin_path` here

2023-04-05 07:27 UTC, micdes-pagopa commented on src/main/31-cloudfront.tf
> +        origin_ssl_protocols   = ["TLSv1"]
```suggestion
        origin_ssl_protocols   = ["TLSv1.2"]
```

2023-04-05 07:27 UTC, micdes-pagopa commented on src/main/31-cloudfront.tf
> +      origin_id   = var.api_gateway_origin_id
```suggestion
      origin_id   = "apigw"
```
I don't expect it to change between environments.

2023-04-05 07:27 UTC, micdes-pagopa commented on src/main/31-cloudfront.tf
- missing API key usage plan and association to stage
- missing CloudFront cache behaviour using the new apigw origin

2023-04-05 08:02 UTC, alessio-creo commented on src/main/31-cloudfront.tf
Dine the first. Please check if the cache behaviour is okay

2023-04-05 14:13 UTC, micdes-pagopa requested changes

2023-04-11 08:51 UTC, micdes-pagopa requested changes

2023-04-11 08:51 UTC, micdes-pagopa commented on src/main/31-cloudfront.tf
> +      path_pattern           = "/eservices/*"
Just a note: there is a quota limit on how many cache behaviours you can have in a distribution (25).
This looks ok to me, but check with the developers how many path patterns they expect.

2023-04-11 15:25 UTC, micdes-pagopa requested changes

2023-04-11 15:25 UTC, micdes-pagopa commented on src/main/98-variables.tf
> +
```suggestion

```
Unused

2023-04-11 15:25 UTC, micdes-pagopa commented on src/main/env/dev/terraform.tfvars
> +api_gateway_origin_id = "api"
```suggestion
```
Unused

2023-04-11 15:48 UTC, merged